name: App Deploy

on:
  # Manual trigger with Environment selection
  workflow_dispatch:
    inputs:
      target_env:
        description: "Select Target Track"
        required: true
        default: "Internal"
        type: choice
        options:
          - Internal
          - Production
      confirm_deploy:
        description: 'Type "deployment" to confirm'
        required: true
        default: ""

concurrency:
  # Hardcoded because build number generated below by the Flutter
  # needs to be always greater than the previous publish to GP.
  # GP also check build number globally, meaning for all tracks
  # (in our case internal and production), and if we start both
  # at the same time and the latter one finished before the former,
  # the former one will fail due to lower build number, because
  # former started with e.g. run_number = 10, and latter with
  # run_number = 11.
  # We will make this dynamic in the future if we decide to have
  # more than production env.
  group: app-deploy
  # Cancelling deploy to Google Play is no good
  cancel-in-progress: false

permissions:
  # For Github release (changelog)
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    # In this app project phase, we will always use production environment
    # for both Internal and Production tracks
    environment: production
    defaults:
      run:
        working-directory: ./app
    steps:
      # 1. Safety & Branch Checks
      - name: Safety Check - Deployment Confirmation
        if: inputs.confirm_deploy != 'deployment'
        working-directory: .
        run: |
          echo "❌ You must type 'deployment' to confirm deployment."
          exit 1

      - name: Safety Check - Production Branch Restriction
        # If target is Production, we MUST be on the 'main' branch
        if: inputs.target_env == 'Production' && github.ref != 'refs/heads/main'
        working-directory: .
        run: |
          echo "❌ Production deployment is only allowed from the 'main' branch."
          echo "Current branch: ${{ github.ref }}"
          exit 1

      # 2. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 3. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      # 4. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"
          channel: "stable"
          cache: true # Cache Flutter SDK

      # 5. Install dependencies
      # "--enforce-lockfile" is used to install exact versions defined in pubspec.yaml,
      # and if there is any diff between pubspec.yaml and pubspec.lock, this will fail
      - name: Get Dependencies
        run: flutter pub get --enforce-lockfile

      # 6. Create/Update .env
      # Using printf because using echo can be a bit dangerous due to
      # possible "$" symbols in the secret, since "$" defines a variable.
      # Using print also requires to define env.
      - name: Create/Update .env
        env:
          APP_ENV: ${{ secrets.APP_ENV }}
        run: printf '%s' "$APP_ENV" > .env

      # 7. Generate Localization
      - name: Generate Localization
        run: flutter gen-l10n

      # 8. Run Build Runner
      - name: Run Build Runner
        # .env file used generated on the step 6
        run: dart run build_runner build --delete-conflicting-outputs --define="envied_generator:envied=path=.env"

      # 9. Decode keystore from base64 format
      - name: Decode Keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: printf '%s' "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/upload-keystore.jks

      # 10. Create key.properties
      # For storeFile it's important to use ${{ github.workspace }} because storeFile is
      # being loaded from the disc by the build.gradle.kts. The rest (storePassword,
      # keyPassword, keyAlias) are just read, and not looked up on the disc.
      - name: Create key.properties
        env:
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        run: |
          {
            printf 'storePassword=%s\n' "$ANDROID_KEY_STORE_PASSWORD"
            printf 'keyPassword=%s\n' "$ANDROID_KEY_PASSWORD"
            printf 'keyAlias=%s\n' "$ANDROID_KEY_ALIAS"
            printf 'storeFile=%s\n' "${{ github.workspace }}/app/android/app/upload-keystore.jks"
          } > android/key.properties

      # 11. Define flavor based on chose environment
      - name: Setup Flavor Variable
        working-directory: .
        run: |
          # In this app project phase, we will always use production environment
          # for both Internal and Production tracks, hence we use here the 
          # production flavor from /android/app/build.gradle.kts
          echo "FLAVOR=production" >> $GITHUB_ENV
          echo "✅ Flavor set to: production"

      # 12. Compute build number
      # Using GITHUB_RUN_ATTEMPT in case of workflow re-runs
      - name: Compute build number
        id: buildno
        working-directory: .
        run: |
          BUILD_NUMBER=$((GITHUB_RUN_NUMBER * 100 + GITHUB_RUN_ATTEMPT))
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT

      # 13. Read version from pubspec
      # Remove any indentation, next line, inline comments
      - name: Read version from pubspec
        id: pubver
        run: |
          VER=$(grep -E '^\s*version:\s*' pubspec.yaml | head -n1 \
            | sed -E 's/^\s*version:\s*//; s/\s*#.*$//' | tr -d '\r')
          VER_NAME="${VER%%+*}"
          echo "ver_name=$VER_NAME" >> $GITHUB_OUTPUT

      # 14. Build release bundle (.aab) with defined flavor
      # Generates build dir in root/app dir (root = ${{ github.workspace }}).
      # Using lib/main_production.dart since currently we use only production flavor.
      - name: Build App Bundle (Release)
        run: flutter build appbundle --release --flavor ${{ env.FLAVOR }} -t lib/main_production.dart --build-number=${{ steps.buildno.outputs.build_number }}

      # 15. Create Google Play API Key JSON
      - name: Create Google Play Service Account JSON
        env:
          GOOGLE_PLAY_JSON: ${{ secrets.GOOGLE_PLAY_DEPLOYER_SERVICE_ACCOUNT_JSON }}
        run: printf '%s' "$GOOGLE_PLAY_JSON" > android/api-key.json

      # 16. Setup Ruby & Fastlane (Fastlane is setup via )
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          # Gemfile location - "uses" steps look at the repository root
          working-directory: app/android

      # Upload artifact step is removed because this is a public repo
      # and uploading .aab and mapping.txt files is not good.

      # 17. Upload to Google Play (Dynamic Track)
      - name: Upload to Google Play
        uses: maierj/fastlane-action@v3.1.0
        with:
          # Inside platform :android block execute commands inside lane deploy_internal
          lane: "android deploy track:${{ (inputs.target_env == 'Production') && 'production' || 'internal' }}"
          subdirectory: "app/android" # "uses" steps look at the repository root
        env:
          AAB_PATH: "${{ github.workspace }}/app/build/app/outputs/bundle/${{ env.FLAVOR }}Release/app-${{ env.FLAVOR }}-release.aab"
          JSON_KEY_FILE: "${{ github.workspace }}/app/android/api-key.json"

      # 18. Create GitHub Release
      # Without .aab and mapping.txt files because repository is public and these
      # files are private, so only tag + release notes.
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: inputs.target_env == 'Production' # Create release only for production
        with:
          tag_name: app-v${{ steps.pubver.outputs.ver_name }}+${{ steps.buildno.outputs.build_number }}
          name: App Release v${{ steps.pubver.outputs.ver_name }}+${{ steps.buildno.outputs.build_number }}
          draft: false # Not a draft, but a direct release
          # Is this version stable (false) or test - since this entire step executes only
          # if the chosen env is production, then false value is correct
          prerelease: false
          generate_release_notes: true # GitHub generates changelog automatically
